style(global): 🚨 run pre-commit on all files and commit linter changes
This is probably fine, everything is fine.

Signed-off-by: Andrei Jiroh Eugenio Halili <ajhalili2006@gmail.com>

diff --git a/devkit/bin/reload-env b/devkit/bin/reload-env
--- a/devkit/bin/reload-env
+++ b/devkit/bin/reload-env
@@ -2,10 +2,9 @@
 
 #
 if [ -f .env ]; then
-  echo "info: Reloading shell environment with latest dotenv changes..."
-  export $(echo $(cat .env | sed 's/#.*//g'| xargs) | envsubst)
+	echo "info: Reloading shell environment with latest dotenv changes..."
+	export $(echo $(cat .env | sed 's/#.*//g' | xargs) | envsubst)
 else
-  echo "error: dotenv file didn't exist, aborting..."
-  exit 1
+	echo "error: dotenv file didn't exist, aborting..."
+	exit 1
 fi
-
