chore(gitlab-cicd): 👷 update CI jobs to make Dazzle builds work + some updates on devkit scripts
We changed the default repo path for our dazzle-up script on root by the way,
but also introduced Skopeo for synchorizing stuff.
It's still an work in progress through, so we'll probably
go into that later. I also run pre-commit for the linting stuff.

Signed-off-by: Andrei Jiroh Eugenio Halili <ajhalili2006@gmail.com>

diff --git a/.gitlab/ci/scripts/docker-build b/.gitlab/ci/scripts/docker-build
--- a/.gitlab/ci/scripts/docker-build
+++ b/.gitlab/ci/scripts/docker-build
@@ -4,35 +4,35 @@ set -e
 
 # set DEBUG var to any vairable to enable debugging
 if [[ $DEBUG != "" ]]; then
-  echo "warning: Debugging for docker-build is enabled."
-  set -x
+	echo "warning: Debugging for docker-build is enabled."
+	set -x
 fi
 
 if [[ $1 == "" ]]; then
-  echo "Usage: $0 CONTEXT_DIR/CONTEXT_DOCKERFILE IMAGE_REPO [CUSTOM_TAG]"
-  echo
-  echo "Required parameters:"
-  echo "  CONTEXT_DIR/CONTEXT_FILE   Relative or abolsute path the the Dockerfile to use for building an image"
-  echo "  IMAGE_REPO                 If left blank, it will push directly to your configured build artifats repo through"
-  echo "                             IMAGE_ARTIFACTS_REPO variable."
-  echo "Optional parameters:"
-  echo "  CUSTOM_TAG                 An custom image tag to use instead of branch-<branch-name> or latest if it's the main branch."
-  echo
-  echo "Needed dependencies: uuidgen (uuid-runtime), sed, grep, basename and dirname and any tool that can build images"
-  echo "from an Dockerfile. Since this script will set DOCKER_BUILDKIT=1 only during docker build invocation, this requires"
-  echo "Docker daemon to be running and the official Docker CLI installed beforehand."
-  echo
-  echo "Supported environment variables:"
-  echo "  IMAGE_ARTIFACTS_REPO       Container image repo for artifacts that this script will be using for"
-  echo "                             storing image artifacts to an container registry instead of the regular"
-  echo "                             GitLab job artifacts."
-  echo "  IMAGE_ARTIFACTS_PUSH       Set it to false to disable pushing build artifacts to an container registry."
-  echo "                             You can push them at a later date."
-  echo "  SKIP_DOCKER_PUSH           Skip pushing images to container registry, which passed to the publish-image"
-  echo "                             utility script. Set this to any value to trigger this."
-  echo "  CI_PROJECT_PATH_SLUG       GitLab project path slug. Use the clone web URl of your project as an reference,"
-  echo "                             minus the GitLab hostname."
-  exit 2
+	echo "Usage: $0 CONTEXT_DIR/CONTEXT_DOCKERFILE IMAGE_REPO [CUSTOM_TAG]"
+	echo
+	echo "Required parameters:"
+	echo "  CONTEXT_DIR/CONTEXT_FILE   Relative or abolsute path the the Dockerfile to use for building an image"
+	echo "  IMAGE_REPO                 If left blank, it will push directly to your configured build artifats repo through"
+	echo "                             IMAGE_ARTIFACTS_REPO variable."
+	echo "Optional parameters:"
+	echo "  CUSTOM_TAG                 An custom image tag to use instead of branch-<branch-name> or latest if it's the main branch."
+	echo
+	echo "Needed dependencies: uuidgen (uuid-runtime), sed, grep, basename and dirname and any tool that can build images"
+	echo "from an Dockerfile. Since this script will set DOCKER_BUILDKIT=1 only during docker build invocation, this requires"
+	echo "Docker daemon to be running and the official Docker CLI installed beforehand."
+	echo
+	echo "Supported environment variables:"
+	echo "  IMAGE_ARTIFACTS_REPO       Container image repo for artifacts that this script will be using for"
+	echo "                             storing image artifacts to an container registry instead of the regular"
+	echo "                             GitLab job artifacts."
+	echo "  IMAGE_ARTIFACTS_PUSH       Set it to false to disable pushing build artifacts to an container registry."
+	echo "                             You can push them at a later date."
+	echo "  SKIP_DOCKER_PUSH           Skip pushing images to container registry, which passed to the publish-image"
+	echo "                             utility script. Set this to any value to trigger this."
+	echo "  CI_PROJECT_PATH_SLUG       GitLab project path slug. Use the clone web URl of your project as an reference,"
+	echo "                             minus the GitLab hostname."
+	exit 2
 fi
 
 # script params
@@ -43,9 +43,9 @@ CUSTOM_TAG=${3:-"latest"}
 
 # if we're inside GitLab CI with these variables, use CI_COMMIT_REF_SLUG var instead
 if [[ $GITLAB_CI == "true" ]]; then
-  GIT_BRANCH=$CI_COMMIT_REF_SLUG
+	GIT_BRANCH=$CI_COMMIT_REF_SLUG
 else
-  GIT_BRANCH="$(git rev-parse --abbrev-ref HEAD | sed 's_/_-_g')"
+	GIT_BRANCH="$(git rev-parse --abbrev-ref HEAD | sed 's_/_-_g')"
 fi
 
 BUILD_ID="ci-build-$GIT_BRANCH"
@@ -63,42 +63,42 @@ COMMIT_SHA=$(git rev-parse HEAD)
 TRIGGER_REBUILD=${TRIGGER_REBUILD:-"false"}
 
 pushArtifact() {
-  echo "========== Pushing build artifact to $IMAGE_ARTIFACTS_REPO =========="
-  docker tag "$IMAGE_NAME:$BUILD_ID" "$IMAGE_ARTIFACTS_REPO:$ARTIFACT_ID"
-  [[ "$CI_MERGE_REQUEST_IID" != "" ]] && docker tag "$IMAGE_NAME:$BUILD_ID" "$IMAGE_ARTIFACTS_REPO:gl-$REPO_SLUG-mr-$CI_MERGE_REQUEST_IID"
-  ./.gitlab/ci/scripts/publish-image "$IMAGE_ARTIFACTS_REPO:$ARTIFACT_ID" "$IMAGE_ARTIFACTS_REPO:gl-$REPO_SLUG-mr-$CI_MERGE_REQUEST_IID"
+	echo "========== Pushing build artifact to $IMAGE_ARTIFACTS_REPO =========="
+	docker tag "$IMAGE_NAME:$BUILD_ID" "$IMAGE_ARTIFACTS_REPO:$ARTIFACT_ID"
+	[[ "$CI_MERGE_REQUEST_IID" != "" ]] && docker tag "$IMAGE_NAME:$BUILD_ID" "$IMAGE_ARTIFACTS_REPO:gl-$REPO_SLUG-mr-$CI_MERGE_REQUEST_IID"
+	./.gitlab/ci/scripts/publish-image "$IMAGE_ARTIFACTS_REPO:$ARTIFACT_ID" "$IMAGE_ARTIFACTS_REPO:gl-$REPO_SLUG-mr-$CI_MERGE_REQUEST_IID"
 }
 
 echo "========== Docker BuildKit starts in 10 seconds =========="
 sleep 10
 # Cache builds from previous built images, as much as possible through the cache-from flags.
 DOCKER_BUILDKIT=1 docker build --tag "$IMAGE_NAME:$BUILD_ID" \
-    --build-arg "buildId=$ARTIFACT_ID" --build-arg "gitRepo=$GIT_REPO" --build-arg "maintainer=$MAINTAINER" \
-    --build-arg "commitId=$COMMIT_SHA" --build-arg "rebuildImage=$TRIGGER_REBUILD" \
-    --build-arg "imageArtifactTagName=$IMAGE_ARTIFACTS_REPO:$ARTIFACT_ID" \
-    --cache-from "quay.io/gitpodified-workspace-images/base:latest" \
-    --cache-from "quay.io/gitpodified-workspace-images/full:latest" \
-    --cache-from "$IMAGE_NAME:$CUSTOM_TAG" \
-    --file "$DIR/$DOCKERFILE" "$DIR"
+	--build-arg "buildId=$ARTIFACT_ID" --build-arg "gitRepo=$GIT_REPO" --build-arg "maintainer=$MAINTAINER" \
+	--build-arg "commitId=$COMMIT_SHA" --build-arg "rebuildImage=$TRIGGER_REBUILD" \
+	--build-arg "imageArtifactTagName=$IMAGE_ARTIFACTS_REPO:$ARTIFACT_ID" \
+	--cache-from "quay.io/gitpodified-workspace-images/base:latest" \
+	--cache-from "quay.io/gitpodified-workspace-images/full:latest" \
+	--cache-from "$IMAGE_NAME:$CUSTOM_TAG" \
+	--file "$DIR/$DOCKERFILE" "$DIR"
 
 # If $2 is blank, it will be only available as an build artifact in IMAGE_ARTIFACTS_REPO, like
 # in merge request builds.
-if [[ $CI_PIPELINE_SOURCE == "merge_request_event" ]] || [[ $IMAGE_NAME == ""  ]]; then
-  pushArtifact
+if [[ $CI_PIPELINE_SOURCE == "merge_request_event" ]] || [[ $IMAGE_NAME == "" ]]; then
+	pushArtifact
 else
-  pushArtifact
-  echo "========== Deploying image to RHQCR =========="
-  if [[ $CUSTOM_TAG != "latest" ]]; then
-     docker tag "$IMAGE_NAME:$BUILD_ID" "$IMAGE_NAME:$CUSTOM_TAG"
-     docker tag "$IMAGE$BUILD_ID" "$IMAGE_NAME:$CUSTOM_TAG-commit-$SHORT_COMMIT_SHA"
-     ./.gitlab/ci/scripts/publish-image "$IMAGE_NAME:$CUSTOM_TAG-commit-$SHORT_COMMIT_SHA" "$IMAGE_NAME:$CUSTOM_TAG"
-  elif [[ $GIT_BRANCH != "recaptime-dev-mainline" ]] && [[ $IMAGE_NAME != "" ]] && [[ $CUSTOM_TAG == "latest" ]]; then
-     docker tag "$IMAGE_NAME:$BUILD_ID" "$IMAGE_NAME:branch-$GIT_BRANCH"
-     docker tag "$IMAGE_NAME:$BUILD_ID" "$IMAGE_NAME:commit-$SHORT_COMMIT_SHA"
-     ./.gitlab/ci/scripts/publish-image "$IMAGE_NAME:branch-$GIT_BRANCH" "$IMAGE_NAME:commit-$SHORT_COMMIT_SHA"
-  elif [[ $GIT_BRANCH == "recaptime-dev-mainline" ]] && [[ $IMAGE_NAME != "" ]] && [[ $CUSTOM_TAG == "latest" ]]; then
-     docker tag "$IMAGE_NAME:$BUILD_ID" "$IMAGE_NAME:latest"
-     docker tag "$IMAGE_NAME:$BUILD_ID" "$IMAGE_NAME:commit-$SHORT_COMMIT_SHA"
-     ./.gitlab/ci/scripts/publish-image "$IMAGE_NAME:latest" "$IMAGE_NAME:commit-$SHORT_COMMIT_SHA"
-  fi
+	pushArtifact
+	echo "========== Deploying image to RHQCR =========="
+	if [[ $CUSTOM_TAG != "latest" ]]; then
+		docker tag "$IMAGE_NAME:$BUILD_ID" "$IMAGE_NAME:$CUSTOM_TAG"
+		docker tag "$IMAGE$BUILD_ID" "$IMAGE_NAME:$CUSTOM_TAG-commit-$SHORT_COMMIT_SHA"
+		./.gitlab/ci/scripts/publish-image "$IMAGE_NAME:$CUSTOM_TAG-commit-$SHORT_COMMIT_SHA" "$IMAGE_NAME:$CUSTOM_TAG"
+	elif [[ $GIT_BRANCH != "recaptime-dev-mainline" ]] && [[ $IMAGE_NAME != "" ]] && [[ $CUSTOM_TAG == "latest" ]]; then
+		docker tag "$IMAGE_NAME:$BUILD_ID" "$IMAGE_NAME:branch-$GIT_BRANCH"
+		docker tag "$IMAGE_NAME:$BUILD_ID" "$IMAGE_NAME:commit-$SHORT_COMMIT_SHA"
+		./.gitlab/ci/scripts/publish-image "$IMAGE_NAME:branch-$GIT_BRANCH" "$IMAGE_NAME:commit-$SHORT_COMMIT_SHA"
+	elif [[ $GIT_BRANCH == "recaptime-dev-mainline" ]] && [[ $IMAGE_NAME != "" ]] && [[ $CUSTOM_TAG == "latest" ]]; then
+		docker tag "$IMAGE_NAME:$BUILD_ID" "$IMAGE_NAME:latest"
+		docker tag "$IMAGE_NAME:$BUILD_ID" "$IMAGE_NAME:commit-$SHORT_COMMIT_SHA"
+		./.gitlab/ci/scripts/publish-image "$IMAGE_NAME:latest" "$IMAGE_NAME:commit-$SHORT_COMMIT_SHA"
+	fi
 fi
diff --git a/.gitlab/ci/scripts/lint-scripts b/.gitlab/ci/scripts/lint-scripts
--- a/.gitlab/ci/scripts/lint-scripts
+++ b/.gitlab/ci/scripts/lint-scripts
@@ -2,18 +2,18 @@
 # shellcheck disable=SC2086
 
 if [[ $1 == "" ]]; then
-  echo "Usage: $0 DIRECTORY [SHELL]"
-  echo
-  echo "Script to recurisively lint scripts with ShellCheck, by default against GNU Bash, based on"
-  echo "instructions at https://go.rtapp.tk/w/shellcheck/Recursiveness"
-  exit 2
+	echo "Usage: $0 DIRECTORY [SHELL]"
+	echo
+	echo "Script to recurisively lint scripts with ShellCheck, by default against GNU Bash, based on"
+	echo "instructions at https://go.rtapp.tk/w/shellcheck/Recursiveness"
+	exit 2
 fi
 
 TARGET_SHELL=${TARGET_SHELL:-$2}
 if [[ $TARGET_SHELL == "zsh" ]]; then
-  echo "error: Linting Zsh scripts is unsupported in ShellCheck. Supported shells include POSIX sh (dash), GNU Bash"
-  echo "error: and ksh."
-  exit 1
+	echo "error: Linting Zsh scripts is unsupported in ShellCheck. Supported shells include POSIX sh (dash), GNU Bash"
+	echo "error: and ksh."
+	exit 1
 fi
 
 # added an ! -path directive to avoid scanning Dockerfiles also
diff --git a/.gitlab/ci/scripts/publish-image b/.gitlab/ci/scripts/publish-image
--- a/.gitlab/ci/scripts/publish-image
+++ b/.gitlab/ci/scripts/publish-image
@@ -1,26 +1,26 @@
 #!/usr/bin/env bash
 
 if [[ $# -eq 0 ]]; then
-  echo "Usage: $0 IMAGE_TAG [...]"
-  echo "Atleast one arg is required to recursively push Docker images to their remote image registries. Make sure to hydrate the Docker CLI"
-  echo "with registry authenication information beforehand to avoid being spammed by the following warnings on your CI logs."
-  echo
-  echo "  \$ $0 non-existent-library-image:tag example.org/docker/hi-mom:1234"
-  echo "  ..."
-  echo "  warning: non-existent-library-image:tag failed to push so it was skipped sliently, sleeping for 5 seconds to ensure we don't get ratelimited..."
-  echo "  ..."
-  echo
-  echo "Tip: If push failed due to Docker CLI not found in PATH and using Podman or the main BuildKit CLI itself, you may need to edit this script as needed"
-  echo "     or even create an /usr/bin/docker symlink pointing to Docker CLI-compartible tool like Podman."
-  exit 2
+	echo "Usage: $0 IMAGE_TAG [...]"
+	echo "Atleast one arg is required to recursively push Docker images to their remote image registries. Make sure to hydrate the Docker CLI"
+	echo "with registry authenication information beforehand to avoid being spammed by the following warnings on your CI logs."
+	echo
+	echo "  \$ $0 non-existent-library-image:tag example.org/docker/hi-mom:1234"
+	echo "  ..."
+	echo "  warning: non-existent-library-image:tag failed to push so it was skipped sliently, sleeping for 5 seconds to ensure we don't get ratelimited..."
+	echo "  ..."
+	echo
+	echo "Tip: If push failed due to Docker CLI not found in PATH and using Podman or the main BuildKit CLI itself, you may need to edit this script as needed"
+	echo "     or even create an /usr/bin/docker symlink pointing to Docker CLI-compartible tool like Podman."
+	exit 2
 fi
 
 for imageTag in "$@"; do
-  echo "====> Pushing image to $imageTag"
-  if ! docker push "$imageTag"; then
-    echo "warning: $imageTag failed to push so it was skipped sliently, sleeping for 5 seconds to ensure we don't get ratelimited..."
-  else
-    echo "info: $imageTag successfully pushed, sleeping for 5 seconds to ensure we don't get ratelimited..."
-  fi
-  sleep 5
+	echo "====> Pushing image to $imageTag"
+	if ! docker push "$imageTag"; then
+		echo "warning: $imageTag failed to push so it was skipped sliently, sleeping for 5 seconds to ensure we don't get ratelimited..."
+	else
+		echo "info: $imageTag successfully pushed, sleeping for 5 seconds to ensure we don't get ratelimited..."
+	fi
+	sleep 5
 done
diff --git a/.gitlab/ci/scripts/wait-docker-tcp b/.gitlab/ci/scripts/wait-docker-tcp
--- a/.gitlab/ci/scripts/wait-docker-tcp
+++ b/.gitlab/ci/scripts/wait-docker-tcp
@@ -4,15 +4,14 @@ DIND_HOSTNAME="${DIND_HOSTNAME:-docker}"
 DIND_PORT="${DIND_PORT:-2375}"
 
 if [[ $DIND_RUN_HEALTHCHECK_BEFORE_BUILD == "" ]]; then
-  echo "error: set DIND_RUN_HEALTHCHECK_BEFORE_BUILD to any value to run me!"
-  exit 1
+	echo "error: set DIND_RUN_HEALTHCHECK_BEFORE_BUILD to any value to run me!"
+	exit 1
 fi
 
-
 if ! command -v nc >>/dev/null; then
-  echo "error: netcat isn't in PATH, perhaps its not installed on your system. Check https://pkgs.org/search/?q=netcat"
-  echo "error: for availability on your Linux distro's package repositories."
-  exit 1
+	echo "error: netcat isn't in PATH, perhaps its not installed on your system. Check https://pkgs.org/search/?q=netcat"
+	echo "error: for availability on your Linux distro's package repositories."
+	exit 1
 fi
 
 echo "========== Wait Docker TCP info =========="
